//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by the PageMethods add-in, version 1.7.2.0
// 
namespace MPClients.PageMethods {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("PageMethodsGenerator", "1.7.2.0")]
    public class User {
        
        public const string PageUrl = "/User.aspx";
        
        public const string TildePageUrl = "~/User.aspx";
        
        private User() {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad(string user) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("user", user, null, false, null));
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                return string.Concat(User.TildePageUrl, paramData);
            }
            else {
                return string.Concat(PageMethodsSettings.BaseUrl, User.PageUrl, paramData);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_Post(string user, System.Web.UI.Control pm_Control) {
            if ((pm_Control == null)) {
                throw new System.ArgumentNullException("pm_Control");
            }
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("user", user, null, false, null));
            string uid = System.Guid.NewGuid().ToString("N").Replace('-', '_');
            string clientFunction = string.Concat("PageMethods_ProcessPost_", uid);
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), "ProcessPost", MetaSapiens.PageMethods.Constants.ProcessPostClientScript, false);
            string url;
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                if ((pm_Control.Page.Request.ApplicationPath == "/")) {
                    url = User.PageUrl;
                }
                else {
                    url = string.Concat(pm_Control.Page.Request.ApplicationPath, User.PageUrl);
                }
            }
            else {
                url = string.Concat(PageMethodsSettings.BaseUrl, User.PageUrl);
            }
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), string.Concat("ProcessPost_", uid), string.Format(System.Globalization.CultureInfo.CurrentCulture, "<script type=\"text/javascript\">\r\n  function {0}()\r\n  {{\r\n    PageMethods_ProcessP" +
                        "ost(\'{1}\', \'{2}\');\r\n  }}\r\n</script>", new object[] {
                            clientFunction,
                            url,
                            paramData}), false);
            return string.Concat("javascript:", clientFunction, "()");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_GetPostData(string user) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("user", user, null, false, null));
            return paramData;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_Raw(string user) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("user", user, null, false, null));
            return string.Concat(User.TildePageUrl, paramData);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("PageMethodsGenerator", "1.7.2.0")]
    public class PageMethodsSettings {
        
        public static string BaseUrl = "";
        
        private PageMethodsSettings() {
        }
    }
}
namespace MPClients.PageMethods {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("PageMethodsGenerator", "1.7.2.0")]
    public class ProductsSearch {
        
        public const string PageUrl = "/ProductsSearch.aspx";
        
        public const string TildePageUrl = "~/ProductsSearch.aspx";
        
        private ProductsSearch() {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad(string user) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("user", user, null, false, null));
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                return string.Concat(ProductsSearch.TildePageUrl, paramData);
            }
            else {
                return string.Concat(PageMethodsSettings.BaseUrl, ProductsSearch.PageUrl, paramData);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_Post(string user, System.Web.UI.Control pm_Control) {
            if ((pm_Control == null)) {
                throw new System.ArgumentNullException("pm_Control");
            }
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("user", user, null, false, null));
            string uid = System.Guid.NewGuid().ToString("N").Replace('-', '_');
            string clientFunction = string.Concat("PageMethods_ProcessPost_", uid);
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), "ProcessPost", MetaSapiens.PageMethods.Constants.ProcessPostClientScript, false);
            string url;
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                if ((pm_Control.Page.Request.ApplicationPath == "/")) {
                    url = ProductsSearch.PageUrl;
                }
                else {
                    url = string.Concat(pm_Control.Page.Request.ApplicationPath, ProductsSearch.PageUrl);
                }
            }
            else {
                url = string.Concat(PageMethodsSettings.BaseUrl, ProductsSearch.PageUrl);
            }
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), string.Concat("ProcessPost_", uid), string.Format(System.Globalization.CultureInfo.CurrentCulture, "<script type=\"text/javascript\">\r\n  function {0}()\r\n  {{\r\n    PageMethods_ProcessP" +
                        "ost(\'{1}\', \'{2}\');\r\n  }}\r\n</script>", new object[] {
                            clientFunction,
                            url,
                            paramData}), false);
            return string.Concat("javascript:", clientFunction, "()");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_GetPostData(string user) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("user", user, null, false, null));
            return paramData;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_Raw(string user) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("user", user, null, false, null));
            return string.Concat(ProductsSearch.TildePageUrl, paramData);
        }
    }
}
namespace MPClients.PageMethods {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("PageMethodsGenerator", "1.7.2.0")]
    public class Message {
        
        public const string PageUrl = "/Message.aspx";
        
        public const string TildePageUrl = "~/Message.aspx";
        
        private Message() {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string LoadById(int messageId) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("messageId", messageId, null, false, null));
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                return string.Concat(Message.TildePageUrl, paramData);
            }
            else {
                return string.Concat(PageMethodsSettings.BaseUrl, Message.PageUrl, paramData);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string LoadById_Post(int messageId, System.Web.UI.Control pm_Control) {
            if ((pm_Control == null)) {
                throw new System.ArgumentNullException("pm_Control");
            }
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("messageId", messageId, null, false, null));
            string uid = System.Guid.NewGuid().ToString("N").Replace('-', '_');
            string clientFunction = string.Concat("PageMethods_ProcessPost_", uid);
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), "ProcessPost", MetaSapiens.PageMethods.Constants.ProcessPostClientScript, false);
            string url;
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                if ((pm_Control.Page.Request.ApplicationPath == "/")) {
                    url = Message.PageUrl;
                }
                else {
                    url = string.Concat(pm_Control.Page.Request.ApplicationPath, Message.PageUrl);
                }
            }
            else {
                url = string.Concat(PageMethodsSettings.BaseUrl, Message.PageUrl);
            }
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), string.Concat("ProcessPost_", uid), string.Format(System.Globalization.CultureInfo.CurrentCulture, "<script type=\"text/javascript\">\r\n  function {0}()\r\n  {{\r\n    PageMethods_ProcessP" +
                        "ost(\'{1}\', \'{2}\');\r\n  }}\r\n</script>", new object[] {
                            clientFunction,
                            url,
                            paramData}), false);
            return string.Concat("javascript:", clientFunction, "()");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string LoadById_GetPostData(int messageId) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("messageId", messageId, null, false, null));
            return paramData;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string LoadById_Raw(int messageId) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("messageId", messageId, null, false, null));
            return string.Concat(Message.TildePageUrl, paramData);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string MsgLoad(string message) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("message", message, null, false, null));
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                return string.Concat(Message.TildePageUrl, paramData);
            }
            else {
                return string.Concat(PageMethodsSettings.BaseUrl, Message.PageUrl, paramData);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string MsgLoad_Post(string message, System.Web.UI.Control pm_Control) {
            if ((pm_Control == null)) {
                throw new System.ArgumentNullException("pm_Control");
            }
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("message", message, null, false, null));
            string uid = System.Guid.NewGuid().ToString("N").Replace('-', '_');
            string clientFunction = string.Concat("PageMethods_ProcessPost_", uid);
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), "ProcessPost", MetaSapiens.PageMethods.Constants.ProcessPostClientScript, false);
            string url;
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                if ((pm_Control.Page.Request.ApplicationPath == "/")) {
                    url = Message.PageUrl;
                }
                else {
                    url = string.Concat(pm_Control.Page.Request.ApplicationPath, Message.PageUrl);
                }
            }
            else {
                url = string.Concat(PageMethodsSettings.BaseUrl, Message.PageUrl);
            }
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), string.Concat("ProcessPost_", uid), string.Format(System.Globalization.CultureInfo.CurrentCulture, "<script type=\"text/javascript\">\r\n  function {0}()\r\n  {{\r\n    PageMethods_ProcessP" +
                        "ost(\'{1}\', \'{2}\');\r\n  }}\r\n</script>", new object[] {
                            clientFunction,
                            url,
                            paramData}), false);
            return string.Concat("javascript:", clientFunction, "()");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string MsgLoad_GetPostData(string message) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("message", message, null, false, null));
            return paramData;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string MsgLoad_Raw(string message) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("message", message, null, false, null));
            return string.Concat(Message.TildePageUrl, paramData);
        }
    }
}
namespace MPClients.PageMethods {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("PageMethodsGenerator", "1.7.2.0")]
    public class OrderEdit {
        
        public const string PageUrl = "/OrderEdit.aspx";
        
        public const string TildePageUrl = "~/OrderEdit.aspx";
        
        private OrderEdit() {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad(string id, bool fromsc) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null), new MetaSapiens.PageMethods.UrlParam("fromsc", fromsc, null, false, null));
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                return string.Concat(OrderEdit.TildePageUrl, paramData);
            }
            else {
                return string.Concat(PageMethodsSettings.BaseUrl, OrderEdit.PageUrl, paramData);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_Post(string id, bool fromsc, System.Web.UI.Control pm_Control) {
            if ((pm_Control == null)) {
                throw new System.ArgumentNullException("pm_Control");
            }
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null), new MetaSapiens.PageMethods.UrlParam("fromsc", fromsc, null, false, null));
            string uid = System.Guid.NewGuid().ToString("N").Replace('-', '_');
            string clientFunction = string.Concat("PageMethods_ProcessPost_", uid);
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), "ProcessPost", MetaSapiens.PageMethods.Constants.ProcessPostClientScript, false);
            string url;
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                if ((pm_Control.Page.Request.ApplicationPath == "/")) {
                    url = OrderEdit.PageUrl;
                }
                else {
                    url = string.Concat(pm_Control.Page.Request.ApplicationPath, OrderEdit.PageUrl);
                }
            }
            else {
                url = string.Concat(PageMethodsSettings.BaseUrl, OrderEdit.PageUrl);
            }
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), string.Concat("ProcessPost_", uid), string.Format(System.Globalization.CultureInfo.CurrentCulture, "<script type=\"text/javascript\">\r\n  function {0}()\r\n  {{\r\n    PageMethods_ProcessP" +
                        "ost(\'{1}\', \'{2}\');\r\n  }}\r\n</script>", new object[] {
                            clientFunction,
                            url,
                            paramData}), false);
            return string.Concat("javascript:", clientFunction, "()");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_GetPostData(string id, bool fromsc) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null), new MetaSapiens.PageMethods.UrlParam("fromsc", fromsc, null, false, null));
            return paramData;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_Raw(string id, bool fromsc) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null), new MetaSapiens.PageMethods.UrlParam("fromsc", fromsc, null, false, null));
            return string.Concat(OrderEdit.TildePageUrl, paramData);
        }
    }
}
namespace MPClients.PageMethods {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("PageMethodsGenerator", "1.7.2.0")]
    public class OrderConfirmation {
        
        public const string PageUrl = "/OrderConfirmation.aspx";
        
        public const string TildePageUrl = "~/OrderConfirmation.aspx";
        
        private OrderConfirmation() {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad(string id) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null));
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                return string.Concat(OrderConfirmation.TildePageUrl, paramData);
            }
            else {
                return string.Concat(PageMethodsSettings.BaseUrl, OrderConfirmation.PageUrl, paramData);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_Post(string id, System.Web.UI.Control pm_Control) {
            if ((pm_Control == null)) {
                throw new System.ArgumentNullException("pm_Control");
            }
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null));
            string uid = System.Guid.NewGuid().ToString("N").Replace('-', '_');
            string clientFunction = string.Concat("PageMethods_ProcessPost_", uid);
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), "ProcessPost", MetaSapiens.PageMethods.Constants.ProcessPostClientScript, false);
            string url;
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                if ((pm_Control.Page.Request.ApplicationPath == "/")) {
                    url = OrderConfirmation.PageUrl;
                }
                else {
                    url = string.Concat(pm_Control.Page.Request.ApplicationPath, OrderConfirmation.PageUrl);
                }
            }
            else {
                url = string.Concat(PageMethodsSettings.BaseUrl, OrderConfirmation.PageUrl);
            }
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), string.Concat("ProcessPost_", uid), string.Format(System.Globalization.CultureInfo.CurrentCulture, "<script type=\"text/javascript\">\r\n  function {0}()\r\n  {{\r\n    PageMethods_ProcessP" +
                        "ost(\'{1}\', \'{2}\');\r\n  }}\r\n</script>", new object[] {
                            clientFunction,
                            url,
                            paramData}), false);
            return string.Concat("javascript:", clientFunction, "()");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_GetPostData(string id) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null));
            return paramData;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_Raw(string id) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null));
            return string.Concat(OrderConfirmation.TildePageUrl, paramData);
        }
    }
}
namespace MPClients.PageMethods {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("PageMethodsGenerator", "1.7.2.0")]
    public class NewsEdit {
        
        public const string PageUrl = "/NewsEdit.aspx";
        
        public const string TildePageUrl = "~/NewsEdit.aspx";
        
        private NewsEdit() {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad(string id) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null));
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                return string.Concat(NewsEdit.TildePageUrl, paramData);
            }
            else {
                return string.Concat(PageMethodsSettings.BaseUrl, NewsEdit.PageUrl, paramData);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_Post(string id, System.Web.UI.Control pm_Control) {
            if ((pm_Control == null)) {
                throw new System.ArgumentNullException("pm_Control");
            }
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null));
            string uid = System.Guid.NewGuid().ToString("N").Replace('-', '_');
            string clientFunction = string.Concat("PageMethods_ProcessPost_", uid);
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), "ProcessPost", MetaSapiens.PageMethods.Constants.ProcessPostClientScript, false);
            string url;
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                if ((pm_Control.Page.Request.ApplicationPath == "/")) {
                    url = NewsEdit.PageUrl;
                }
                else {
                    url = string.Concat(pm_Control.Page.Request.ApplicationPath, NewsEdit.PageUrl);
                }
            }
            else {
                url = string.Concat(PageMethodsSettings.BaseUrl, NewsEdit.PageUrl);
            }
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), string.Concat("ProcessPost_", uid), string.Format(System.Globalization.CultureInfo.CurrentCulture, "<script type=\"text/javascript\">\r\n  function {0}()\r\n  {{\r\n    PageMethods_ProcessP" +
                        "ost(\'{1}\', \'{2}\');\r\n  }}\r\n</script>", new object[] {
                            clientFunction,
                            url,
                            paramData}), false);
            return string.Concat("javascript:", clientFunction, "()");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_GetPostData(string id) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null));
            return paramData;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoLoad_Raw(string id) {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString(new MetaSapiens.PageMethods.UrlParam("id", id, null, false, null));
            return string.Concat(NewsEdit.TildePageUrl, paramData);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoCreate() {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString("DoCreate");
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                return string.Concat(NewsEdit.TildePageUrl, paramData);
            }
            else {
                return string.Concat(PageMethodsSettings.BaseUrl, NewsEdit.PageUrl, paramData);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoCreate_Post(System.Web.UI.Control pm_Control) {
            if ((pm_Control == null)) {
                throw new System.ArgumentNullException("pm_Control");
            }
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString("DoCreate");
            string uid = System.Guid.NewGuid().ToString("N").Replace('-', '_');
            string clientFunction = string.Concat("PageMethods_ProcessPost_", uid);
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), "ProcessPost", MetaSapiens.PageMethods.Constants.ProcessPostClientScript, false);
            string url;
            if (string.IsNullOrEmpty(PageMethodsSettings.BaseUrl)) {
                if ((pm_Control.Page.Request.ApplicationPath == "/")) {
                    url = NewsEdit.PageUrl;
                }
                else {
                    url = string.Concat(pm_Control.Page.Request.ApplicationPath, NewsEdit.PageUrl);
                }
            }
            else {
                url = string.Concat(PageMethodsSettings.BaseUrl, NewsEdit.PageUrl);
            }
            pm_Control.Page.ClientScript.RegisterClientScriptBlock(pm_Control.Page.GetType(), string.Concat("ProcessPost_", uid), string.Format(System.Globalization.CultureInfo.CurrentCulture, "<script type=\"text/javascript\">\r\n  function {0}()\r\n  {{\r\n    PageMethods_ProcessP" +
                        "ost(\'{1}\', \'{2}\');\r\n  }}\r\n</script>", new object[] {
                            clientFunction,
                            url,
                            paramData}), false);
            return string.Concat("javascript:", clientFunction, "()");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoCreate_GetPostData() {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString("DoCreate");
            return paramData;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static string DoCreate_Raw() {
            string paramData = MetaSapiens.PageMethods.PageMethodsEngine.BuildQueryString("DoCreate");
            return string.Concat(NewsEdit.TildePageUrl, paramData);
        }
    }
}
